/* Absolute Dental Production Catalog (31 Products, Active Batch Stock & Pricing) */
const INITIAL_PRODUCTS = [
  {
    "id": "d02e821e-91e3-4ed4-869e-f636142d8247",
    "nameAr": "Artificial Teeth - Central Incisor",
    "nameEn": "Artificial Teeth - Central Incisor",
    "sku": "DEN-d02e",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 1.15,
    "sellingPrice": 2,
    "wholesalePrice": 1.15,
    "retailPrice": 2,
    "stock": 53,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/d02e821e-91e3-4ed4-869e-f636142d8247.jpg",
    "subject": "dental-anatomy"
  },
  {
    "id": "5528000b-cde4-4b27-8745-7956dc0e4b78",
    "nameAr": "Artificial Teeth - Lower First Molar",
    "nameEn": "Artificial Teeth - Lower First Molar",
    "sku": "DEN-5528",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 1.15,
    "sellingPrice": 2,
    "wholesalePrice": 1.15,
    "retailPrice": 2,
    "stock": 52,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/5528000b-cde4-4b27-8745-7956dc0e4b78.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "6c359465-a522-4654-933f-a64c627c6b38",
    "nameAr": "Carving wax (Full Box) - 3 Pieces",
    "nameEn": "Carving wax (Full Box) - 3 Pieces",
    "sku": "DEN-6c35",
    "category": "تشريح الأسنان (سنة 1)",
    "costPrice": 4,
    "sellingPrice": 5,
    "wholesalePrice": 4,
    "retailPrice": 5,
    "stock": 13,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/6c359465-a522-4654-933f-a64c627c6b38.jpg",
    "subject": "dental-anatomy"
  },
  {
    "id": "106ad65c-3074-4cfb-8643-840f36f833f5",
    "nameAr": "Carving wax - Single Piece",
    "nameEn": "Carving wax - Single Piece",
    "sku": "DEN-106a",
    "category": "تشريح الأسنان (سنة 1)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/106ad65c-3074-4cfb-8643-840f36f833f5.jpg",
    "subject": "dental-anatomy"
  },
  {
    "id": "5b7d387c-f150-4e64-90fe-b21ac1249ebc",
    "nameAr": "Dental Mouth Mirror",
    "nameEn": "Dental Mouth Mirror",
    "sku": "DEN-5b7d",
    "category": "أدوات الفحص والعيادة",
    "costPrice": 11,
    "sellingPrice": 15,
    "wholesalePrice": 11,
    "retailPrice": 15,
    "stock": 17,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/5b7d387c-f150-4e64-90fe-b21ac1249ebc.jpg",
    "subject": "fixed-prosthodontics"
  },
  {
    "id": "ba48f5b5-38c2-4571-94f5-67be7d38aab3",
    "nameAr": "Dental Spatula",
    "nameEn": "Dental Spatula",
    "sku": "DEN-ba48",
    "category": "مواد طب الأسنان (سنة 1)",
    "costPrice": 15,
    "sellingPrice": 17,
    "wholesalePrice": 15,
    "retailPrice": 17,
    "stock": 13,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/ba48f5b5-38c2-4571-94f5-67be7d38aab3.jpg",
    "subject": "dental-materials"
  },
  {
    "id": "8a2c351d-359c-4f5e-8c37-3d4ecb1eba19",
    "nameAr": "Fissure Bur - SF 46",
    "nameEn": "Fissure Bur - SF 46",
    "sku": "DEN-8a2c",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/8a2c351d-359c-4f5e-8c37-3d4ecb1eba19.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "e625888c-c1b0-4479-9117-76a1215a75f4",
    "nameAr": "Fissure bur - CD 52F (red)",
    "nameEn": "Fissure bur - CD 52F (red)",
    "sku": "DEN-e625",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/e625888c-c1b0-4479-9117-76a1215a75f4.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "2ebc663e-0967-4d6a-b8be-b07b9e84659c",
    "nameAr": "Inverted cone bur - SI 46",
    "nameEn": "Inverted cone bur - SI 46",
    "sku": "DEN-2ebc",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/2ebc663e-0967-4d6a-b8be-b07b9e84659c.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "7eaed4a6-5d82-480e-b35e-0ca2d15c90dc",
    "nameAr": "Light Curing Acrylic Resin Baseplates",
    "nameEn": "Light Curing Acrylic Resin Baseplates",
    "sku": "DEN-7eae",
    "category": "صناعة الأسنان المتحركة (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/7eaed4a6-5d82-480e-b35e-0ca2d15c90dc.jpg",
    "subject": "removable-prosthodontics"
  },
  {
    "id": "c78f57a0-54d0-4602-aa05-d92a82398a2f",
    "nameAr": "Long taper with flat end - TF12 (blue)",
    "nameEn": "Long taper with flat end - TF12 (blue)",
    "sku": "DEN-c78f",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/c78f57a0-54d0-4602-aa05-d92a82398a2f.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "36e0d204-3613-44b0-b74e-0ba7869420c4",
    "nameAr": "Long taper with flat end - TF12 (yellow)",
    "nameEn": "Long taper with flat end - TF12 (yellow)",
    "sku": "DEN-36e0",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/36e0d204-3613-44b0-b74e-0ba7869420c4.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "ad31f7c7-d710-4622-8e3f-377b9c657818",
    "nameAr": "NSK High speed handpiece",
    "nameEn": "NSK High speed handpiece",
    "sku": "DEN-ad31",
    "category": "كونس وكراون (سنة 2)",
    "costPrice": 115,
    "sellingPrice": 135,
    "wholesalePrice": 115,
    "retailPrice": 135,
    "stock": 18,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/ad31f7c7-d710-4622-8e3f-377b9c657818.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "af6c097d-6f53-4ce3-8d52-f9b9fc095295",
    "nameAr": "Periodontal Probe",
    "nameEn": "Periodontal Probe",
    "sku": "DEN-af6c",
    "category": "أدوات الفحص واللثة",
    "costPrice": 12,
    "sellingPrice": 15,
    "wholesalePrice": 12,
    "retailPrice": 15,
    "stock": 16,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/af6c097d-6f53-4ce3-8d52-f9b9fc095295.jpg",
    "subject": "periodontics"
  },
  {
    "id": "76f62cd7-df40-4e85-97d1-6fb63b09e2f1",
    "nameAr": "Round bur - BR 49",
    "nameEn": "Round bur - BR 49",
    "sku": "DEN-76f6",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/76f62cd7-df40-4e85-97d1-6fb63b09e2f1.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "4caab5ef-1c9c-411e-8b6e-76781a07fd97",
    "nameAr": "Round burr - BR46",
    "nameEn": "Round burr - BR46",
    "sku": "DEN-4caa",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/4caab5ef-1c9c-411e-8b6e-76781a07fd97.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "75fb4e12-d06f-4a0e-b7ac-d571b9e996ab",
    "nameAr": "طقم رابر بول + بلاستيك سباتيولا",
    "nameEn": "Rubber bowl + plastic spatula",
    "sku": "DEN-75fb",
    "category": "مواد طب الأسنان (سنة 1)",
    "costPrice": 11,
    "sellingPrice": 15,
    "wholesalePrice": 11,
    "retailPrice": 15,
    "stock": 21,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/75fb4e12-d06f-4a0e-b7ac-d571b9e996ab.jpg",
    "subject": "dental-materials",
    "notes": "21 طقم: 15 بودري + أبيض، 5 أزرق + أبيض، 1 أخضر + أبيض"
  },
  {
    "id": "0c18deeb-a571-419b-adf2-8060db42d8cf",
    "nameAr": "Student Glass Slab (Mixing Glass Slab)",
    "nameEn": "Student Glass Slab (Mixing Glass Slab)",
    "sku": "DEN-0c18",
    "category": "مواد طب الأسنان (سنة 1)",
    "costPrice": 1,
    "sellingPrice": 3,
    "wholesalePrice": 1,
    "retailPrice": 3,
    "stock": 5,
    "minStock": 0,
    "supplier": "",
    "status": "منخفض",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/0c18deeb-a571-419b-adf2-8060db42d8cf.jpg",
    "subject": "dental-materials"
  },
  {
    "id": "fa042791-6d8d-48c1-8f60-f1a103162a1e",
    "nameAr": "Study cast + high-speed NSK hand piece",
    "nameEn": "Study cast + high-speed NSK hand piece",
    "sku": "DEN-fa04",
    "category": "كاستات وقبضات (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/fa042791-6d8d-48c1-8f60-f1a103162a1e.jpg",
    "subject": "fixed-prosthodontics"
  },
  {
    "id": "c9442057-a22f-4ce8-a237-d37f2024146f",
    "nameAr": "Torch 261 Jet Lighter",
    "nameEn": "Torch 261 Jet Lighter",
    "sku": "DEN-c944",
    "category": "تشريح ومواد (سنة 1)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/c9442057-a22f-4ce8-a237-d37f2024146f.jpg",
    "subject": "dental-anatomy"
  },
  {
    "id": "e009eaf4-f041-4706-b27d-daa394e512d3",
    "nameAr": "Wax carver",
    "nameEn": "Wax carver",
    "sku": "DEN-e009",
    "category": "تشريح الأسنان (سنة 1)",
    "costPrice": 12,
    "sellingPrice": 15,
    "wholesalePrice": 12,
    "retailPrice": 15,
    "stock": 10,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/e009eaf4-f041-4706-b27d-daa394e512d3.jpg",
    "subject": "dental-anatomy"
  },
  {
    "id": "c554e6ff-3a55-4e36-aed6-562f70601342",
    "nameAr": "Wax knife",
    "nameEn": "Wax knife",
    "sku": "DEN-c554",
    "category": "تشريح الأسنان (سنة 1)",
    "costPrice": 12,
    "sellingPrice": 15,
    "wholesalePrice": 12,
    "retailPrice": 15,
    "stock": 12,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/c554e6ff-3a55-4e36-aed6-562f70601342.jpg",
    "subject": "dental-anatomy"
  },
  {
    "id": "72e1069c-4319-42ff-a38c-2af8f8e4e546",
    "nameAr": "Wax sheet",
    "nameEn": "Wax sheet",
    "sku": "DEN-72e1",
    "category": "تشريح الأسنان (سنة 1)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/72e1069c-4319-42ff-a38c-2af8f8e4e546.jpg",
    "subject": "dental-anatomy"
  },
  {
    "id": "d2a56c58-bf46-47aa-b803-6546aa7491c5",
    "nameAr": "Wheel Round Bur - WR 13",
    "nameEn": "Wheel Round Bur - WR 13",
    "sku": "DEN-d2a5",
    "category": "صناعة الأسنان الثابتة (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/d2a56c58-bf46-47aa-b803-6546aa7491c5.jpg",
    "subject": "fixed-prosthodontics"
  },
  {
    "id": "2a8f9bde-fb3f-485d-a1bd-d62aa0b83556",
    "nameAr": "Wide spatula",
    "nameEn": "Wide spatula",
    "sku": "DEN-2a8f",
    "category": "مواد طب الأسنان (سنة 1)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/2a8f9bde-fb3f-485d-a1bd-d62aa0b83556.jpg",
    "subject": "dental-materials"
  },
  {
    "id": "8f344bd9-91ec-4787-8371-f489cccf635e",
    "nameAr": "dental cast",
    "nameEn": "dental cast",
    "sku": "DEN-8f34",
    "category": "كاستات تعليمية (سنة 2)",
    "costPrice": 105,
    "sellingPrice": 125,
    "wholesalePrice": 105,
    "retailPrice": 125,
    "stock": 10,
    "minStock": 0,
    "supplier": "",
    "status": "متوفر",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/8f344bd9-91ec-4787-8371-f489cccf635e.jpg",
    "subject": "fixed-prosthodontics"
  },
  {
    "id": "187f6429-fee1-4f50-8edc-2a18bac1de35",
    "nameAr": "diamond flame bur - FO 32 (yellow)",
    "nameEn": "diamond flame bur - FO 32 (yellow)",
    "sku": "DEN-187f",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/187f6429-fee1-4f50-8edc-2a18bac1de35.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "627bdb62-3364-497b-8aa6-3b911ad78f26",
    "nameAr": "niddle bur - TC 10 (Blue)",
    "nameEn": "niddle bur - TC 10 (Blue)",
    "sku": "DEN-627b",
    "category": "علاج الأسنان التحفظي (سنة 2)",
    "costPrice": 0,
    "sellingPrice": 0,
    "wholesalePrice": 0,
    "retailPrice": 0,
    "stock": 0,
    "minStock": 0,
    "supplier": "",
    "status": "نافد",
    "image": "https://api.kurofangs.id.ly/storage/v1/object/public/pdf-sheets/smylodent-products/627bdb62-3364-497b-8aa6-3b911ad78f26.jpg",
    "subject": "restorative-dentistry"
  },
  {
    "id": "8806943f-d3bf-443b-b623-7002b354a355",
    "nameAr": "قبضة توربين أصلية COXO C207 (بنفسجي)",
    "nameEn": "COXO High-Speed Handpiece C207 (Purple)",
    "sku": "DEN-8806",
    "category": "كونس وكراون (سنة 2)",
    "costPrice": 215,
    "sellingPrice": 225,
    "wholesalePrice": 215,
    "retailPrice": 225,
    "stock": 6,
    "minStock": 0,
    "supplier": "",
    "status": "منخفض",
    "image": "https://7ij0d.github.io/absolute-dental/coxo-handpiece-c207.png",
    "subject": "fixed-prosthodontics"
  },
  {
    "id": "item-penlight-clear",
    "nameAr": "مفك فحص شفاف (قلم فحص قياسي)",
    "nameEn": "Transparent Examination Penlight",
    "sku": "DEN-MFK-01",
    "category": "أدوات الفحص والعيادة",
    "costPrice": 1.75,
    "sellingPrice": 4,
    "wholesalePrice": 1.75,
    "retailPrice": 4,
    "stock": 3,
    "minStock": 5,
    "supplier": "",
    "status": "منخفض",
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
    "subject": "fixed-prosthodontics"
  },
  {
    "id": "item-penlight-led",
    "nameAr": "مفك فحص مع ضوء (Medical LED)",
    "nameEn": "Medical LED Penlight",
    "sku": "DEN-MFK-02",
    "category": "أدوات الفحص والعيادة",
    "costPrice": 2.5,
    "sellingPrice": 5,
    "wholesalePrice": 2.5,
    "retailPrice": 5,
    "stock": 9,
    "minStock": 5,
    "supplier": "",
    "status": "منخفض",
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
    "subject": "fixed-prosthodontics"
  }
];
const INITIAL_ORDERS = [];
const INITIAL_PURCHASES = [];
const INITIAL_EXPENSES = [];
const INITIAL_ACTIVITY = [];
if (typeof window !== 'undefined') {
  window.ERP_SEEDED_PRODUCTS = INITIAL_PRODUCTS;
  window.ERP_SEEDED_ORDERS = INITIAL_ORDERS;
  window.ERP_SEEDED_PURCHASES = INITIAL_PURCHASES;
}
